[package]
name = "package-deployer"
version = "1.0.0"
authors = []

[addresses]

package_deployer = "_"
deployer_admin_initial = "_"

[dev-addresses]
package_deployer = "0x42"
deployer_admin_initial = "0x43"

object_code_deterministic_deployment = "0x10"
aptos_extensions = "0x12"
aptos_extensions_deployer = "0x13"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.object-code-deterministic-deployment]
local = "../object-code-deterministic-deployment"

[dependencies.AptosExtensions]
git = "https://github.com/yeap-finance/stablecoin-aptos.git"
rev= "master"
subdir = "./packages/aptos_extensions"

[dev-dependencies]
