[package]
name = "object-code-deterministic-deployment"
version = "1.0.0"
authors = []
upgrade_policy = "immutable"

[addresses]
object_code_deterministic_deployment = "_"

[dev-addresses]
object_code_deterministic_deployment = "0x10"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
