# Yeaptor deployment configuration (v1)
#
# This file declares:
# - publisher aliases and their on-chain addresses
# - deployments: an ordered array; each item maps to a single resource account, defined by
#   (publisher + seed), and contains its own ordered list of packages to deploy. Each package is
#   an object with { address_name, path }.
#
# Ordering:
# - Deployments: processed in the order they appear in [[deployments]].
# - Packages: executed in the order they appear in the deployment's packages array. No explicit dependencies.
#
# Packages listed under the same deployment are deployed to the same resource account
# derived from (publisher address, seed).

format_version = 1
yeaptor_address = "0x1"
[publishers]
# Alias -> on-chain address
yeap-multisig = "0x10"

[named-addresses]
# dependencies addresses


# Deployment 1
[[deployments]]
# Provide seed as UTF-8 text or hex (0x...).
publisher = "yeap-multisig"
seed = "core-v1"

packages = [
  { address_name = "ra_code_deployment", path = "packages/resource-account-code-deployment" },
  { address_name = "proxy_account", path = "packages/proxy-account" },
]

# Deployment 2
[[deployments]]
publisher = "yeap-multisig"
seed = "payments-v1"
packages = [
]
# Place entries in desired order; no explicit dependency keywords are supported.

